### PR TITLE
Subprogram ports strict check

### LINKED ISSUE #660: Package Subprogram Declaration Can Mismatch Definition
The VHDL requires the subprogram declarations to match the definitions exactly.  When the names of the arguments passed to subprograms are different, the error is produced.  If the implicit values of `constant` or `in` are used, though, they are not checked.  The following compiles with no issue:

```vhdl
package pack is

    function blah(x : integer) return integer ;

    procedure dosomething(x : in integer) ;

end package ;

package body pack is

    function blah(constant x : in integer) return integer is
    begin
        return x + 1;
    end function ;

    procedure dosomething(constant x : integer) is
    begin
    end procedure ;

end package body ;
```

RivieraPRO gives the following output:
```
COMP96 Compile Package "pack"
COMP96 Compile Package Body "pack"
COMP96 The currently compiled unit contains subprogram specifications with minor inconsistencies between the declaration and the body.
COMP96 Use -relax to ignore such inconsistencies.
COMP96 ERROR COMP96_0321: "Subprogram specification of the body must conform to the subprogram specification of the declaration." "test.vhdl" 11 59
COMP96 ERROR COMP96_0321: "Subprogram specification of the body must conform to the subprogram specification of the declaration." "test.vhdl" 16 49
COMP96 Compile failure 2 Errors 0 Warnings  Analysis time :  0.0 [ms]
```

With `-relax`, the output gives no warnings.

GHDL also gives an error:
```
test.vhdl:11:14:error: body of function "blah" does not conform with specification at line 3:14
    function blah(constant x : in integer) return integer is
             ^
test.vhdl:11:14:note: (you can use -frelaxed to turn this error into a warning)
    function blah(constant x : in integer) return integer is
             ^
test.vhdl:16:15:error: body of procedure "dosomething" does not conform with specification at line 5:15
    procedure dosomething(constant x : integer) is
```

... and turns into a warning with `-frelaxed`:
```
test.vhdl:11:14:warning: body of function "blah" does not conform with specification at line 3:14 [-Wconformance]
    function blah(constant x : in integer) return integer is
             ^
test.vhdl:16:15:warning: body of procedure "dosomething" does not conform with specification at line 5:15 [-Wconformance]
    procedure dosomething(constant x : integer) is
```

### PR DESCRIPTION
**Pull request by Blebowski**
An attempt to fix #660.

Checks if `CONSTANT` and `IN` are placed "equally explicitly" in both subprogram
body and subprogram specification.

### CODE REVIEW

File: src/sem.c [hunk 1]
```diff
@@ -1466,6 +1466,12 @@ static bool sem_check_func_decl(tree_t t, nametab_t *tab)
 static bool sem_compare_interfaces(tree_t dport, tree_t bport,
                                    int nth, tree_t body, const char *what)
 {
+   tree_flags_t dflags = tree_flags(dport);
+   tree_flags_t bflags = tree_flags(bport);
+
+   diag_level_t nexp_match_elevel = opt_get_int(OPT_RELAXED) ?
```
Comment (nickg) [inline src/sem.c:1472]: You can use `pedantic_diag()` for this (see examples elsewhere in this file).

**Review by nickg — APPROVED** [review]
This looks reasonable, thanks.
